### ISSUE TITLE
Launcher can't find org.mcphackers.launchwrapper.Launch

### ISSUE THREAD

**Issue by 4194304** [MCPHackers/LaunchWrapper#11]
Installing LaunchWrapper through the provided instructions both through making a component, and through adding it manually, doesn't work.

OpenJDK 8 build 422 JRE was used here.

I tried changing the amount of memory allocated to the instance from 4096MB to 1024MB, and it did not change the result.

https://mclo.gs/D0If1Qj

[org.mcphackers.launchwrapper.json](https://github.com/user-attachments/files/16830165/org.mcphackers.launchwrapper.json)
[launchwrapper.json](https://github.com/user-attachments/files/16830167/launchwrapper.json)

**Comment by Lassebq** [comment]
Read
> [!IMPORTANT]
> notice in <https://github.com/MCPHackers/LaunchWrapper/blob/main/MultiMC.md>

**Comment by Lassebq** [comment]
If the built jar isn't there, add it to that location.
`instance/libraries` also works.

**Comment by 4194304** [comment]
Whoops I am an idiot

**Comment by Lassebq** [comment]
:tada:
