### ISSUE TITLE
Cannot connect to Forge server with LW active

### ISSUE THREAD

**Issue by DanyGames2014** [MCPHackers/LaunchWrapper#13]
I can't connect to a Forge r1.2.5 server with LaunchWrapper active on client.

Forge Client + Vanilla Server works
Vanilla Client + Vanilla Server works
Forge Client + Forge Server doesnt work

When it happens the client gets stuck on the "Logging In" screen, it doesnt hang, i can press Cancel just fine. The last log messages are 
Client : `Connecting to localhost, 25565`
Server : `[INFO] DanyGames2014 [/127.0.0.1:56509] logged in with entity id 127 at (114.9375, 101.0, 523.90625)`
Nothing else.

I tried putting the server in offline mode, didnt help.

**Comment by Lassebq** [comment]
Does Forge Client + Forge Server work without LW?

**Comment by Lassebq** [comment]
Okay, can confirm it does

**Comment by Lassebq** [comment]
Try 20b443209e7ef253d44764539143e3a5f268e73e
