### ISSUE TITLE
LaunchWrapper crashes upon launch.

### ISSUE THREAD

**Issue by jadenquinn** [MCPHackers/LaunchWrapper#15]
https://mclo.gs/S6SVd8i

**Comment by Lassebq** [comment]
Please use latest commit

**Comment by jadenquinn** [comment]
I still get the same crash.

**Comment by jadenquinn** [comment]
As it turns out, the instructions were not complete. I had to go in and rename some things in the JSON from 1.0-SNAPSHOT to 1.1-SNAPSHOT, had to manually create that 1.1-SNAPSHOT folder in the libraries structure, and had to manually copy in the required JAR. The docs should say all of this but don't. Is this assumed knowledge?

**Comment by Lassebq** [comment]
Instructions weren't updated to include up to date version string. Also, the -SNAPSHOT prefix is added unless running build like this:
```sh
RELEASE=1 ./gradlew build
```
If you have trouble creating or renaming folders, consider using `mkdir`:
```sh
mkdir org/mcphackers/launchwrapper/<insert version here, with -SNAPSHOT or not, depending on JSON contents>/launchwrapper-<insert version again>.jar
```
And yes, this is assumed knowledge as it's currently in a (stale) development and the current target audience is assumed to be experienced in Java and using gradle. PRs are welcome
