### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Thensi72** [MCPHackers/LaunchWrapper#3]
i know this is very basic but i dont know how to install and use this because i dont see any explanation on how to use this here

**Comment by Lassebq** [comment]
Everything you need to know is in README.md I have no idea how you could've missed it.

**Comment by Thensi72** [comment]
idk which things are the "wrapper libraries" so im not sure how to use it

**Comment by Lassebq** [comment]
As stated by README.md, the easy way would be to use [BetterJSONs](https://github.com/MCPHackers/BetterJSONs). Otherwise, you could use it to manually launch the game using a command line.

**Comment by Lassebq** [comment]
BetterJSONSs contain all of the game libraries + wrapper dependencies, while build.gradle specifies LaunchWrapper dependencies.

**Comment by Thensi72** [comment]
but it says only for launcher with same as vanilla launcher

**Comment by Lassebq** [comment]
> If you are using Official Launcher (or any other launcher which follows the same versions folder structure)
e. g. TL Legacy (or as it is called now Legacy Launcher), TLauncher, the Official Minecraft Launcher from minecraft.net. I'm sure there are plenty more implementations.

**Comment by Lassebq** [comment]
Pick one, install and run the game the easy way. You don't look like you're ready to do it manually

**Comment by Thensi72** [comment]
ok
