### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by kimoVoid** [MCPHackers/LaunchWrapper#5]
In older versions of the game (only tested in b1.7.3 and b1.6.6), while using LaunchWrapper, the game is unable to authenticate the player on Multiplayer servers. The server does have online-mode patched and it works with the Betacraft proxy for example, but it always fails to verify the user while using LaunchWrapper, resulting in the "Failed to verify username!" screen while trying to join the server.

**Comment by Lassebq** [comment]
Please test with latest commit. Contact me on Discord `@lassebq` if you're looking for builds

**Comment by Lassebq** [comment]
Can confirm, authentication works now.
